Feat/multiple track audios
mauricioabreu/mosaic-video pull request #17
Opened 2024-01-15 15:23 UTC by luiscovelo

2024-01-15 17:01 UTC, mauricioabreu requested changes
Good job so far.

2024-01-15 17:01 UTC, mauricioabreu commented on internal/mosaic/command/builder.go
> +		if m.WithAudio {
Most of the mosaics I have ever seen in my entire life have only the audio of the first video.
Maybe we need this option to have multiple choices:
* No audio (`no_audio`)
* First input only (`first_input`)
* All inputs (`all_inputs`)

2024-01-15 18:38 UTC, luiscovelo commented on internal/mosaic/command/builder.go
> +		if m.WithAudio {
Oh, right!

Theses options can be a new struct, like as "Audio"?

Example:

```go
type Audio struct {
	NoAudio    bool `json:"no_audio"`
	FirstInput bool `json:"first_input"`
	AllInputs  bool `json:"all_inputs"`
}
```
or 

```go
type Audio struct {
	Off        bool `json:"off"`
	FirstInput bool `json:"first_input"`
	AllInputs  bool `json:"all_inputs"`
}
```

What's your option about this?

2024-01-15 19:09 UTC, mauricioabreu commented on internal/mosaic/command/builder.go
> +		if m.WithAudio {
The field could be an enum with these 3 options.
Imagine you are creating a mosaic through an admin. This admin could provide a dropdown with these 3 options

2024-01-15 19:20 UTC, luiscovelo commented on internal/mosaic/command/builder.go
> +		if m.WithAudio {
Right,

Like this:

```go
type Audio string

const (
	NoAudio    string = "no_audio"
	FirstInput string = "first_input"
	AllInputs  string = "all_inputs"
)

type (
	Position struct {
		X int
		Y int
	}
	Media struct {
		URL      string `json:"url"`
		Position Position
		Scale    string
	}

	Mosaic struct {
		Name          string  `json:"name"`
		BackgroundURL string  `json:"background_url"`
		Medias        []Media `json:"medias"`
		Audio         Audio   `json:"audio"`
	}
)
```

Using the `Audio` as a type, we can to assign three methods to validate audio options, such as: IsNoAudio(), IsFirstInput() or IsAllInputs().

```go
type Audio string

func (a Audio) IsNoAudio() bool {
	return a == Audio(NoAudio)
}

func (a Audio) IsFirstInput() bool {
	return a == Audio(FirstInput)
}

func (a Audio) IsAllInputs() bool {
	return a == Audio(AllInputs)
}
```

What do you think?

2024-01-15 19:53 UTC, mauricioabreu commented on internal/mosaic/command/builder.go
> +		if m.WithAudio {
I agree with the constant approach and the Audio type, pretty cool!

2024-01-15 19:55 UTC, luiscovelo commented on internal/mosaic/command/builder.go
> +		if m.WithAudio {
Good, i'll fixed it.

2024-01-15 20:49 UTC, luiscovelo commented
@mauricioabreu,

Based in our conversations, i fixed to use a Audio as a enum type.

2024-01-15 22:02 UTC, mauricioabreu commented
@luiscovelo good! How did it look like in the player? Did it play smooth with the multiple audios option?

2024-01-15 23:21 UTC, luiscovelo commented
@mauricioabreu,

I tested using VLC player, I had to download a mosaic content from bucket and to import on VLC.

I'll to add this options in the HLS player into another PR, I need to evaluate in how to make in HLS.js library, but in VLC player worked as well.

2024-01-16 03:11 UTC, mauricioabreu approved these changes
Good job!

2024-01-16 03:11 UTC, merged